# Generated by Django 3.2.4 on 2021-06-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
