# Generated by Django 3.2.4 on 2021-06-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210622_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=75, primary_key=True, serialize=False, verbose_name='Correo de Usuario'),
        ),
    ]
