# Generated by Django 3.2.4 on 2021-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210622_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default=1, max_length=75, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
